// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {indexer} from '../models';

export function ImagePreview(arg1:string):Promise<string>;

export function OpenInVSCode(arg1:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function Rescan():Promise<void>;

export function RevealPath(arg1:string):Promise<void>;

export function Search(arg1:indexer.SearchRequest):Promise<Array<indexer.Entry>>;

export function Status():Promise<indexer.Status>;
