// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImagePreview(arg1) {
  return window['go']['main']['App']['ImagePreview'](arg1);
}

export function OpenInVSCode(arg1) {
  return window['go']['main']['App']['OpenInVSCode'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function Rescan() {
  return window['go']['main']['App']['Rescan']();
}

export function RevealPath(arg1) {
  return window['go']['main']['App']['RevealPath'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
